export const mockedResponse = {
      id: 'A000360',
      member_id: 'A000360',
      first_name: 'Lamar',
      middle_name: '',
      last_name: 'Alexander',
      suffix: null,
      date_of_birth: '1940-07-03',
      gender: 'M',
      url: null,
      times_topics_url:
        'http://topics.nytimes.com/top/reference/timestopics/people/a/lamar_alexander/index.html',
      times_tag: '',
      govtrack_id: '300002',
      cspan_id: '5',
      votesmart_id: '15691',
      icpsr_id: '40304',
      twitter_account: 'SenAlexander',
      facebook_account: 'senatorlamaralexander',
      youtube_account: 'lamaralexander',
      crp_id: 'N00009888',
      google_entity_id: '/m/01rbs3',
      rss_url: 'https://www.alexander.senate.gov/public/?a=RSS.Feed',
      in_office: false,
      current_party: 'R',
      most_recent_vote: '2020-12-30',
      last_updated: '2020-12-30 19:01:18 -0500',
      roles: [
        {
          congress: '116',
          chamber: 'Senate',
          title: 'Senator, 2nd Class',
          short_title: 'Sen.',
          state: 'TN',
          party: 'R',
          leadership_role: null,
          fec_candidate_id: 'S2TN00058',
          seniority: '17',
          senate_class: '2',
          state_rank: 'senior',
          lis_id: 'S289',
          ocd_id: 'ocd-division/country:us/state:tn',
          start_date: '2019-01-03',
          end_date: '2021-01-03',
          office: '455 Dirksen Senate Office Building',
          phone: '202-224-4944',
          fax: '202-228-3398',
          contact_form:
            'http://www.alexander.senate.gov/public/index.cfm?p=Email',
          cook_pvi: null,
          dw_nominate: 0.324,
          ideal_point: null,
          next_election: '2020',
          total_votes: 717,
          missed_votes: 133,
          total_present: 0,
          bills_sponsored: 22,
          bills_cosponsored: 153,
          missed_votes_pct: 18.55,
          votes_with_party_pct: 96.55,
          votes_against_party_pct: 3.45,
          committees: [
            {
              name: 'Committee on Energy and Natural Resources',
              code: 'SSEG',
              api_uri:
                'https://api.propublica.org/congress/v1/116/senate/committees/SSEG.json',
              side: 'majority',
              title: 'Member',
              rank_in_party: 10,
              begin_date: '2019-01-09',
              end_date: '2021-01-03',
            },
            {
              name: 'Committee on Rules and Administration',
              code: 'SSRA',
              api_uri:
                'https://api.propublica.org/congress/v1/116/senate/committees/SSRA.json',
              side: 'majority',
              title: 'Member',
              rank_in_party: 3,
              begin_date: '2019-01-09',
              end_date: '2021-01-03',
            },
            {
              name: 'Committee on Health, Education, Labor, and Pensions',
              code: 'SSHR',
              api_uri:
                'https://api.propublica.org/congress/v1/116/senate/committees/SSHR.json',
              side: 'majority',
              title: 'Chair',
              rank_in_party: 1,
              begin_date: '2019-01-09',
              end_date: '2021-01-03',
            },
            {
              name: 'Committee on Appropriations',
              code: 'SSAP',
              api_uri:
                'https://api.propublica.org/congress/v1/116/senate/committees/SSAP.json',
              side: 'majority',
              title: 'Member',
              rank_in_party: 3,
              begin_date: '2019-01-09',
              end_date: '2021-01-03',
            },
          ],
          subcommittees: [
            {
              name: 'Energy',
              code: 'SSEG01',
              parent_committee_id: 'SSEG',
              api_uri:
                'https://api.propublica.org/congress/v1/116/senate/committees/SSEG/subcommittees/SSEG01.json',
              side: 'majority',
              title: 'Member',
              rank_in_party: 8,
              begin_date: '2019-02-05',
              end_date: '2021-01-03',
            },
            {
              name: 'National Parks Subcommittee',
              code: 'SSEG04',
              parent_committee_id: 'SSEG',
              api_uri:
                'https://api.propublica.org/congress/v1/116/senate/committees/SSEG/subcommittees/SSEG04.json',
              side: 'majority',
              title: 'Member',
              rank_in_party: 6,
              begin_date: '2019-02-05',
              end_date: '2021-01-03',
            },
          ],
        },
        {
          congress: '115',
          chamber: 'Senate',
          title: 'Senator, 2nd Class',
          short_title: 'Sen.',
          state: 'TN',
          party: 'R',
          leadership_role: null,
          fec_candidate_id: 'S2TN00058',
          seniority: '15',
          senate_class: '2',
          state_rank: 'senior',
          lis_id: 'S289',
          ocd_id: 'ocd-division/country:us/state:tn',
          start_date: '2017-01-03',
          end_date: '2019-01-03',
          office: '455 Dirksen Senate Office Building',
          phone: '202-224-4944',
          fax: '202-228-3398',
          contact_form:
            'http://www.alexander.senate.gov/public/index.cfm?p=Email',
          cook_pvi: null,
          dw_nominate: 0.323,
          ideal_point: null,
          next_election: '2020',
          total_votes: 599,
          missed_votes: 27,
          total_present: 0,
          bills_sponsored: 31,
          bills_cosponsored: 123,
          missed_votes_pct: 4.51,
          votes_with_party_pct: 97.0,
          votes_against_party_pct: 3.0,
          committees: [
            {
              name: 'Committee on Appropriations',
              code: 'SSAP',
              api_uri:
                'https://api.propublica.org/congress/v1/115/senate/committees/SSAP.json',
              side: 'majority',
              title: 'Member',
              rank_in_party: 3,
              begin_date: '2017-01-03',
              end_date: '2019-01-03',
            },
            {
              name: 'Committee on Energy and Natural Resources',
              code: 'SSEG',
              api_uri:
                'https://api.propublica.org/congress/v1/115/senate/committees/SSEG.json',
              side: 'majority',
              title: 'Member',
              rank_in_party: 8,
              begin_date: '2017-01-03',
              end_date: '2019-01-03',
            },
            {
              name: 'Committee on Health, Education, Labor, and Pensions',
              code: 'SSHR',
              api_uri:
                'https://api.propublica.org/congress/v1/115/senate/committees/SSHR.json',
              side: 'majority',
              title: 'Chair',
              rank_in_party: 1,
              begin_date: '2017-01-03',
              end_date: '2019-01-03',
            },
            {
              name: 'Committee on Rules and Administration',
              code: 'SSRA',
              api_uri:
                'https://api.propublica.org/congress/v1/115/senate/committees/SSRA.json',
              side: 'majority',
              title: 'Member',
              rank_in_party: 4,
              begin_date: '2017-01-03',
              end_date: '2019-01-03',
            },
          ],
          subcommittees: [
            {
              name: 'Commerce, Justice, Science, and Related Agencies Subcommittee',
              code: 'SSAP16',
              parent_committee_id: 'SSAP',
              api_uri:
                'https://api.propublica.org/congress/v1/115/senate/committees/SSAP/subcommittees/SSAP16.json',
              side: 'majority',
              title: 'Member',
              rank_in_party: 2,
              begin_date: '',
              end_date: '2019-01-03',
            },
            {
              name: 'Defense Subcommittee',
              code: 'SSAP02',
              parent_committee_id: 'SSAP',
              api_uri:
                'https://api.propublica.org/congress/v1/115/senate/committees/SSAP/subcommittees/SSAP02.json',
              side: 'majority',
              title: 'Member',
              rank_in_party: 4,
              begin_date: '',
              end_date: '2019-01-03',
            },
            {
              name: 'Interior, Environment, and Related Agencies Subcommittee',
              code: 'SSAP17',
              parent_committee_id: 'SSAP',
              api_uri:
                'https://api.propublica.org/congress/v1/115/senate/committees/SSAP/subcommittees/SSAP17.json',
              side: 'majority',
              title: 'Member',
              rank_in_party: 3,
              begin_date: '',
              end_date: '2019-01-03',
            },
            {
              name: 'Labor, Health and Human Services, and Education, and Related Agencies',
              code: 'SSAP18',
              parent_committee_id: 'SSAP',
              api_uri:
                'https://api.propublica.org/congress/v1/115/senate/committees/SSAP/subcommittees/SSAP18.json',
              side: 'majority',
              title: 'Member',
              rank_in_party: 4,
              begin_date: '',
              end_date: '2019-01-03',
            },
            {
              name: 'Energy and Water Development Subcommittee',
              code: 'SSAP22',
              parent_committee_id: 'SSAP',
              api_uri:
                'https://api.propublica.org/congress/v1/115/senate/committees/SSAP/subcommittees/SSAP22.json',
              side: 'majority',
              title: 'Chair',
              rank_in_party: 1,
              begin_date: '',
              end_date: '2019-01-03',
            },
            {
              name: 'Transportation, Housing and Urban Development, and Related Agencies',
              code: 'SSAP24',
              parent_committee_id: 'SSAP',
              api_uri:
                'https://api.propublica.org/congress/v1/115/senate/committees/SSAP/subcommittees/SSAP24.json',
              side: 'majority',
              title: 'Member',
              rank_in_party: 3,
              begin_date: '',
              end_date: '2019-01-03',
            },
            {
              name: 'Energy',
              code: 'SSEG01',
              parent_committee_id: 'SSEG',
              api_uri:
                'https://api.propublica.org/congress/v1/115/senate/committees/SSEG/subcommittees/SSEG01.json',
              side: 'majority',
              title: 'Member',
              rank_in_party: 5,
              begin_date: '',
              end_date: '2019-01-03',
            },
            {
              name: 'National Parks Subcommittee',
              code: 'SSEG04',
              parent_committee_id: 'SSEG',
              api_uri:
                'https://api.propublica.org/congress/v1/115/senate/committees/SSEG/subcommittees/SSEG04.json',
              side: 'majority',
              title: 'Member',
              rank_in_party: 5,
              begin_date: '',
              end_date: '2019-01-03',
            },
            {
              name: 'Public Lands, Forests, and Mining Subcommittee',
              code: 'SSEG03',
              parent_committee_id: 'SSEG',
              api_uri:
                'https://api.propublica.org/congress/v1/115/senate/committees/SSEG/subcommittees/SSEG03.json',
              side: 'majority',
              title: 'Member',
              rank_in_party: 7,
              begin_date: '',
              end_date: '2019-01-03',
            },
          ],
        },
      ],
};
